name: Docker
env:
  fsf: fsdfs

on:
  push:
    branches: 
      - '*'
    tags: 
      - '*'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yaml
  build:
#     needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files_change
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo '${{ steps.files_change.outputs.files }}'
        
#       - name: Build docker image ${fsf}
#         run: docker build ./ -t hectopus:${GITHUB_REF##*/}
        
