name: Build

on:
  push:
    tags: 
      - '*'
  pull_request:
    branches:
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2  
