name: Docker

on:
  pull_request:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  tags:
    - '*'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  build:
    if: jobs.run-test.status == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build ./ -t ${{ IMAGE_NAME }}
