name: Docker
env:
  fsf: fsdfs

on:
  push:
    tags: 
      - '*'
  pull_request:
    branches: 
      - 'master'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF}
  build:
    needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image $fsf
        run: docker build ./ -t hectopus:${GITHUB_REF##*/}
        
