name: Docker

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - id: step-test
        run: echo 'Hello World!'
  build:
    needs: run-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build ./ -t ${GITHUB_BASE_REF}
        
