name: Docker

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ${{ GITHUB_REF:11 }}

jobs:
  build:
    if: jobs.run-test.status == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build ./ -t ${{ IMAGE_NAME }}
