name: Docker
env:
  fsf: fsdfs

on:
  push:
    branches: 
      - '*'
    tags: 
      - '*'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y yamllint
      - run: yamllint ./
  build:
    needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image ${fsf}
        run: docker build ./ -t hectopus:${GITHUB_REF##*/}
        
