name: Docker
env:
  fsf: fsdfs

on:
  push:
    branches: 
      - '*'
    tags: 
      - '*'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yaml
  build:
#     needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          which git && \
          git --no-pager diff --name-only $GITHUB_REF##*/..$GITHUB_HEAD_REF
      - run: |
          for i in $(git --no-pager diff --name-only ${GITHUB_REF##*/}..${GITHUB_BASE_REF} | egrep -v "^docs/|^modules/|^scripts/")
          do 
            dirname $i
          done | sort -u 
#       - name: Build docker image ${fsf}
#         run: docker build ./ -t hectopus:${GITHUB_REF##*/}
        
