name: Build

on:
  push:
    tags: 
      - '*'
  pull_request:
    branches:
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        helm-version: [v2.16.3]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2  
