name: Docker
env:
  fsf: fsdfs

on:
  push:
    tags: 
      - '*'
  pull_request:
    branches: 
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image $fsf
        if: job.run-test == 'success'
        run: docker build ./ -t hectopus:${GITHUB_REF:11}
        
