name: Docker

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    if: jobs.run-test.status == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build ./ -t ${{ IMAGE_NAME }}
        env:
          IMAGE_NAME: ${GITHUB_REF##*/}
